---
- name: Acquire and Set an IP Address
  hosts: localhost
  gather_facts: no
  
  vars:
  - ip_addr: 192.168.100.110
  - netmask: 255.255.255.0
  - gateway: 192.168.1.254
  - server_api_url: "https://cfme.onepoint.ninja"
  - server_api_user: admin
  - server_api_pwd: "2+2=VingtDeux"

  tasks:
 
  - debug: var=miq_provision_id
  - debug: var=miq_provision_request_id
  - debug: var=ip_addr
  - debug: var=netmask
  - debug: var=gateway
  - debug: var=server_api_user
  - debug:
      msg: "Onepoint - Ansible Test POC"

#  - debug:
#      var: "{{ item }}"
#    with_items:
#      - "{{ ip_addr }}"
#      - "{{ netmask }}"
#      - "{{ gateway }}"
#      - "{{ server_api_url }}"
#      - "{{ server_api_user }}"

  - name: Update Task with New IP and Hostname Information
    uri:
#      url: "https://cfme.onepoint.ninja/api/provision_requests/1000000000004/request_tasks/1000000000004"
      url: "https://cfme.onepoint.ninja/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
      method: POST
      body_format: json
      body:
        action: edit
        resource:
          options:
            addr_mode: ["static", "Static"]
            ip_addr: "{{ ip_addr }}"
            subnet_mask: "{{ netmask }}"
            gateway: "{{ gateway }}"
      validate_certs: no
      #headers:
        #X-Auth-Token: "{{ manageiq.api_token }}"
      url_username: "{{ server_api_user }}"
      url_password: "{{ server_api_pwd }}"
      body_format: json
      status_code: 200
