---
- name: Acquire and Set an IP Address
  hosts: localhost
  gather_facts: no
  
  vars:
    vm:
      VMtestIT101:
        ip: 192.168.150.101
      VMtestIT102:
        ip: 192.168.150.102
      VMtestIT103:
        ip: 192.168.150.103
      VMtestIT104:
        ip: 192.168.150.104
      VMtestIT105:
        ip: 192.168.150.105
      VMtestIT106:
        ip: 192.168.150.106
      VMtestIT107:
        ip: 192.168.150.107
      VMtestIT108:
        ip: 192.168.150.108
      VMtestIT109:
        ip: 192.168.150.109
      VMtestIT110:
        ip: 192.168.150.110
    netmask: 255.255.255.0
    gateway: 192.168.1.254
    server_api_url: "https://cfme.onepoint.ninja"
    server_api_user: admin
    server_api_pwd: "2+2=VingtDeux"


  tasks:

  - debug: var=miq_provision_id
  - debug: var=miq_provision_request_id
  - debug: var=ip_addr
  - debug: var=netmask
  - debug: var=gateway
  - debug: var=server_api_user
  - debug:
      msg: "Onepoint - Ansible Test POC - Provision request N° {{ miq_provision_request_id }} with the VM {{vm_name}}"

#  - name: Retrieve VM informations
#    uri:
#      url: "https://cfme.onepoint.ninja/api/provision_requests/{{ miq_provision_request_id }}"
#      method: GET
#      body_format: json
#      validate_certs: no
#      url_username: "{{ server_api_user }}"
#      url_password: "{{ server_api_pwd }}"
#    register: GET_API_response
#    ignore_errors: True

#  - name: Show the API response
#    debug:
#      var: GET_API_response

  - name: Update Task with New IP and Hostname Information
    uri:
      url: "https://cfme.onepoint.ninja/api/provision_requests/{{ miq_provision_request_id }}/request_tasks/{{ miq_provision_id }}"
      method: POST
      body_format: json
      body:
        action: edit
        resource:
          options:
            addr_mode: ["static", "Static"]
            ip_addr: "{{vm[vm_name].ip}}"
            subnet_mask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            current_tab_key: customize
            dns_servers: 8.8.8.8
            linux_domain_name: onepoint.ninja
            sysprep_custom_spec: [null, null]
            sysprep_enabled: ["fields", "Specification"]
      validate_certs: no
      url_username: "{{ server_api_user }}"
      url_password: "{{ server_api_pwd }}"
      body_format: json
      status_code: 200
    register: POST_API_response

  - name: Show the API answer
    debug:
      var: POST_API_response

  - name: Results
    debug:
      msg: "The message is '{{ POST_API_response.json.message }}'"

#  - name: Results
#    debug:
#      msg: "{{item}}"
#    with_items:
#      - "{{ POST_API_response.json.message }}"
#      - "{{ POST_API_response.json.ip_addr }}"
